- name: 1.3.1 Install AIDE
  yum: name=aide state=present
- name: "EXTRA: Initializing AIDE if needed (takes a short while)"
  action: shell /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz' 
        creates=/var/lib/aide/aide.db.gz
- name: 1.3.2 Implement Periodic Execution of File Integrity ( Install Cron )
  yum: name=vixie-cron state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split(".")[0]|int == 5
- name: 1.3.2 Implement Periodic Execution of File Integrity
  cron: name="Run AIDE (CIS 1.3.2)" minute="0" hour="5" job="/usr/sbin/aide --check"
