- name: 1.5.1 Set User/Group Owner on /etc/grub.conf
  file: path=/boot/grub/grub.conf owner=root group=root
- name: 1.5.2 Set Permissions on /etc/grub.conf
  file: path=/boot/grub/grub.conf mode=0400
- name: 1.5.3 Set Boot Loader Password
  shell: cat /etc/grub.conf
  register: pwgrub
- shell: echo "Please set the grub password"
  when: pwgrub.stdout.find('password') != 0
- name: 1.5.4 Disable Interactive Boot
  lineinfile: dest=/etc/sysconfig/init regexp=^SINGLE= line=SINGLE=/sbin/sulogin
- name: 1.5.5 Disable Interactive Boot
  lineinfile: dest=/etc/sysconfig/init regexp=^PROMPT= line=PROMPT=no
