- name: 2.1.1 Remove telnet-server
  yum: name=telnet-server state=absent
- name: 2.1.2 Remove telnet Clients
  yum: name=telnet state=absent
- name: 2.1.2 Add nc package so there is tool to diagnose connections
  yum: name=nc state=present
- name: 2.1.3 Remove rsh-server 
  yum: name=rsh-server state=absent
- name: 2.1.4 Remove rsh
  yum: name=rsh state=absent
- name: 2.1.5 Remove NIS Client
  yum: name=ypbind state=absent
- name: 2.1.6 Remove NIS Server
  yum: name=ypserv state=absent
- name: 2.1.7 Remove tftp
  yum: name=tftp state=absent
- name: 2.1.8 Remove tftp-server
  yum: name=tftp-server state=absent
- name: 2.1.9 Remove talk
  yum: name=talk state=absent
- name: 2.1.10 Remove talk-server
  yum: name=talk-server state=absent
- name: 2.1.11 Remove xinetd
  yum: name=xinetd state=absent
- name: 2.1.12 Disable chargen-dgram
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.13 Disable chargen-stream
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.14 Disable daytime-dgram
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.15 Disable daytime-stream
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.16 Disable echo-dgram
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.17 Disable echo-stream
  debug: msg="Not Required. xinetd is already uninstalled."
- name: 2.1.18 Disable tcpmux-server
  debug: msg="Not Required. xinetd is already uninstalled."