- name: 4.1.1 Disable IP Forwarding
  sysctl: name=net.ipv4.ip_forward value=0 state=present
- name: 4.1.2 Disable Send Packet Redirects (all)
  sysctl: name=net.ipv4.conf.all.send_redirects value=0 state=present
- name: 4.1.2 Disable Send Packet Redirects (default)
  sysctl: name=net.ipv4.conf.default.send_redirects value=0 state=present