- name: 5.1.1 Install the rsyslog package
  yum: name=rsyslog state=present
- name: 5.1.2 Activate the rsyslog Service
  service: name=rsyslog state=started
- name: 5.1.4 Create and Set Permissions on rsyslog Log Files
  file: path={{ item }} owner=root group=root mode=0600
  with_items:
    - /var/log/messages
    - /var/log/secure
    - /var/log/maillog
    - /var/log/cron
    - /var/log/spooler
    - /var/log/boot.log
- name: 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host
  lineinfile: dest=/etc/rsyslog.conf state=present regexp="^\*\.\* @" line="*.* @@loghost.example.com" insertafter=EOF
