- name: 7.1.1 Set Password Expiration Days
  lineinfile: dest=/etc/login.defs regexp="^PASS_MAX_DAYS" line='PASS_MAX_DAYS 90'
- name: 7.1.2 Set Password Change Minimum Number of Days 
  lineinfile: dest=/etc/login.defs regexp="^PASS_MIN_DAYS" line='PASS_MIN_DAYS 7'
- name: 7.1.3 Set Password Expiring Warning Days
  lineinfile: dest=/etc/login.defs regexp="^PASS_WARN_AGE" line='PASS_WARN_AGE 7'
#- name: 7.2 Disable System Accounts 
- name: 7.3 Set Default Group for root Account
  user: name=root group=root state=present
- name: 7.4 Set Default umask for Users
  lineinfile: dest=/etc/bashrc regexp="^umask" line='umask 077'
- name: 7.4 Set Default umask for Users
  lineinfile: dest=/etc/profile regexp="^umask" line='umask 077'
- name: 7.4 Set Default umask for Users
  lineinfile: dest=/etc/csh.cshrc regexp="^umask" line='umask 077'
- name: 7.5 Lock Inactive User Accounts
  lineinfile: dest=/etc/default/useradd regexp="^INACTIVE" line='INACTIVE=35'
