- command: ls -ld /etc/passwd
  register: passwd_perms
- name: 9.1.2 Verify Permissions on /etc/passwd
  debug: msg="{{ passwd_perms.stdout }}"
- command: ls -ld /etc/shadow
  register: shadow_perms
- name: 9.1.3 Verify Permissions on /etc/shadow
  debug: msg="{{ shadow_perms.stdout }}"
- command: ls -ld /etc/gshadow
  register: gshadow_perms
- name: 9.1.4 Verify Permissions on /etc/gshadow 
  debug: msg="{{ gshadow_perms.stdout }}"
- command: ls -ld /etc/group
  register: group_perms
- name: 9.1.5 Verify Permissions on /etc/group
  debug: msg="{{ group_perms.stdout }}"
- name: 9.1.6 Verify User/Group Ownership on /etc/passwd
  debug: msg="{{ passwd_perms.stdout }}"
- name: 9.1.7 Verify User/Group Ownership on /etc/shadow 
  debug: msg="{{ shadow_perms.stdout }}"
- name: 9.1.8 Verify User/Group Ownership on /etc/gshadow
  debug: msg="{{ gshadow_perms.stdout }}"
- name: 9.1.9 Verify User/Group Ownership on /etc/group
  debug: msg="{{ group_perms.stdout }}"
#- name: 9.1.11 Find Un-owned Files and Directories 
#- name: 9.1.12 Find Un-grouped Files and Directories
#- command: /bin/cat /etc/shadow | /bin/awk -F":" '($2 == "" ) { print $1 " does not have a password "}'
#  register: emptypasswords
#- name: 9.2.1 Ensure Password Fields are Not Empty
#  debug: msg="{{ emptypasswords.stdout }}"
- command: "/bin/grep '^+:' /etc/passwd"
  register: passwd_plus
  ignore_errors: True
- name: 9.2.2 Verify No Legacy "+" Entries Exist in /etc/passwd File
  debug: msg="{{ passwd_plus.stdout }}"
- command: "/bin/grep '^+:' /etc/shadow"
  register: shadow_plus
  ignore_errors: True
- name: 9.2.3 Verify No Legacy "+" Entries Exist in /etc/shadow File
  debug: msg="{{ shadow_plus.stdout }}"
- command: "/bin/grep '^+:' /etc/group"
  register: group_plus
  ignore_errors: True
- name: 9.2.4 Verify No Legacy "+" Entries Exist in /etc/group File
  debug: msg="{{ group_plus.stdout }}"
#- name: 9.2.5 Verify No UID 0 Accounts Exist Other Than root
#- name: 9.2.6 Ensure root PATH Integrity 
#- name: 9.2.7 Check Permissions on User Home Directories
#- name: 9.2.8 Check User Dot File Permissions
#- name: 9.2.9 Check Permissions on User .netrc Files
#- name: 9.2.10 Check for Presence of User .rhosts Files
#- name: 9.2.11 Check Groups in /etc/passwd
#- name: 9.2.12 Check That Users Are Assigned Valid Home Directories
#- name: 9.2.13 Check User Home Directory Ownership
#- name: 9.2.14 Check for Duplicate UIDs
#- name: 9.2.15 Check for Duplicate GIDs
#- name: 9.2.16 Check That Reserved UIDs Are Assigned to System Accounts
#- name: 9.2.17 Check for Duplicate User Names
#- name: 9.2.18 Check for Duplicate Group Names
#- name: 9.2.19 Check for Presence of User .netrc Files 
#- name: 9.2.20 Check for Presence of User .forward Files 
